#!/usr/bin/env bash
#creando un while para imrpimir el contrnido ademas del IFS
while IFS=: read -r username group_id home_directory shell user_id password user_id_info
do
	echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < "/etc/passwd"
