#!/usr/bin/env bash
#creando un bucle while if para despliegar best school
COUNTER=1
while [ $COUNTER -le 10 ]; do
	echo "Best School"
	if [ $COUNTER -eq 9 ];
	then
		echo "Hi"
	fi
	((COUNTER ++))
done
