#!/usr/bin/env bash
#creando un while if elif alterando al despliegue del 1 al 10
COUNTER=1
while [ $COUNTER -le 10 ]; do
	if [ $COUNTER -eq 4 ];
	then
		echo "bad luck"
	elif [ $COUNTER -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((COUNTER++))
done
