#!/usr/bin/env bash
#creando un ehile utilizando case para 3 condiciones
COUNTER=1
while [ $COUNTER -le 20 ];
do
	echo $COUNTER
	case $COUNTER in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((COUNTER++))
done
