#!/usr/bin/env bash
#creando un while que muestre durante todo las 12 horas y 59 minutos
hora=0
while [ $hora -le 12 ];do
	echo "Hour: $hora"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		minute=$((minute+1))
	done
	hora=$((hora+1))
done
