#!/usr/bin/env bash
#creando un if y else para mostrar info de school
if [ -e school ];
then
	if [ -s school ];
	then
		echo school file is not empty
	else
		echo school file is empty
	fi
	if [ -f school ];
	then
		echo school is a regular file	
	fi
	echo school file exists
else
	echo school file does not exist
fi
