#!/usr/bin/env bash
#vamos a crear varias condiciones y depende de eso ejecutamos los trap
trap "echo I hate the kill command" 15
trap "echo Y U no love me?!" 2
trap "rm -r /var/run/myscript.pid; exit" 3 15

echo $$ >> /var/run/myscript.pid

while true
do
        echo "To infinity and beyond"
        sleep 2
done
