#!/usr/bin/env bash
#
go(){
	./manage_my_process &
	echo $! > /var/run/my_process.pid
}

pare(){
        pkill -f manage_my_process &
        rm -r /var/run/my_process.pid
}


case $1 in
	start) go; echo "manage_my_process started";;
	stop) pare; echo "manage_my_process stopped";;
	restart) pare; go; echo "manage_my_process restarted";;
	*) echo "Usage: manage_my_process {start|stop|restart}";;
esac
